build:
    environment:
        php:
            version: 5.6.9
        mysql: 5.5
    project_setup:
        before:
            - sudo service start mysql || true
            - mysql -e "CREATE DATABASE test_database_name"
    tests:
        before:
            command: 'phpunit  --configuration `pwd`/phpunit.xml'